### ISSUE TITLE
Fix deployment at `yarn workspace webgui build`

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/convert.glossarist.org#1]
The step at `yarn workspace webgui build` is failing on GHA.

This has been failing since this commit by @strogonoff :
https://github.com/glossarist/migration-adapters/commit/1dae3dde098e9e2760025c254140decb53e7be81

**Comment by ronaldtse** [comment]
Only after this is done the website will properly deploy.

**Comment by strogonoff** [comment]
I don’t know what’s going on, it’s very confusing. The outcome of `yarn workspace webgui build --debug --distdir=$(pwd)/webgui-dist` is very different from mine, even if I run my script in bash (same shell GHA uses).

Here it doesn’t even output any debug logs, as if `--debug` is stripped out. That would show where the files are written and why there is no webgui-dist to upload as artifact.

@ribose-jeffreylau or @kwkwan  do you know what might be going on?

The line is line 52 in https://github.com/glossarist/convert.glossarist.org/blob/main/.github/workflows/build_deploy.yml#L52.

**Comment by strogonoff** [comment]
I give up—hopefully someone more proficient with GHA can find why it works locally but not in GHA.

To check, you can 1) check out https://github.com/glossarist/migration-adapters and 2) run the same command on your machine (`yarn workspace webgui build --debug --distdir=$(pwd)/webgui-dist`). Note that you need Node 20 (though 18 may work).

**Comment by strogonoff** [comment]
The conclusion is Node incompatibility. Webgui build fails on GHA with any Node 20, with Node 18.19, but succeeds with Node 18.18.2.
