### ISSUE TITLE
Replace `GH_PANERON_CI_TOKEN` (org secret) with `paneron-ci`'s PAT

### ISSUE THREAD

**Issue by ribose-jeffreylau** [glossarist/convert.glossarist.org#4]
It seems that right now, `GH_PANERON_CI_TOKEN` is actually my own personal token 🙈 

The (classic) token would need access to `repo`.

cc: @ronaldtse

**Comment by ronaldtse** [comment]
@ribose-jeffreylau replaced with the access token of the "paneron-ci" account. Thanks!
